c: Emit struct designated initializers in declaration order (#282)
This is needed to compile the generated code with g++:
error: designator order for field ‘zEncCapability::zperms’ does not match declaration order in ‘zEncCapability’