c: Emit tuple designated initializers in declaration order
This is required to compile the generated code with a C++ compiler:
issue232_2.c: In function ‘ztuple_z8z5enumz0zzEzCz0z5enumz0zzEz9 zeful_unpack_forwards(zeful)’:
issue232_2.c:295:86: error: designator order for field ‘ztuple_z8z5enumz0zzEzCz0z5enumz0zzEz9::ztup0’ does not match declaration order in ‘ztuple_z8z5enumz0zzEzCz0z5enumz0zzEz9’
  295 |   struct ztuple_z8z5enumz0zzEzCz0z5enumz0zzEz9 zcbz36 = { .ztup1 = zEA, .ztup0 = zEA };